CREATE TABLE T_RESOURCE (
		ID INTEGER NOT NULL,
		TYPE VARCHAR(255),
		VALUE VARCHAR(255)
	);

CREATE TABLE T_USER (
		ID INTEGER NOT NULL,
		DISABLED SMALLINT NOT NULL,
		EMAIL VARCHAR(255),
		NAME VARCHAR(255),
		PASSWORD VARCHAR(255),
		USERNAME VARCHAR(255)
	);

CREATE TABLE T_ROLE (
		ID INTEGER NOT NULL,
		DESCRIPTION VARCHAR(255),
		NAME VARCHAR(255)
	);

CREATE TABLE T_ROLE_RESOURCE (
		ROLE_ID INTEGER NOT NULL,
		RESOURCE_ID INTEGER NOT NULL
	);

CREATE TABLE T_USER_ROLE (
		USER_ID INTEGER NOT NULL,
		ROLE_ID INTEGER NOT NULL
	);

ALTER TABLE T_USER_ROLE ADD CONSTRAINT SQL090223195852140 PRIMARY KEY (USER_ID, ROLE_ID);

ALTER TABLE T_ROLE ADD CONSTRAINT SQL090223195851290 PRIMARY KEY (ID);

ALTER TABLE T_ROLE_RESOURCE ADD CONSTRAINT SQL090223195851760 PRIMARY KEY (ROLE_ID, RESOURCE_ID);

ALTER TABLE T_RESOURCE ADD CONSTRAINT SQL090223195851070 PRIMARY KEY (ID);

ALTER TABLE T_USER ADD CONSTRAINT SQL090223195851960 PRIMARY KEY (ID);

ALTER TABLE T_USER_ROLE ADD CONSTRAINT FK331DEE5F97972F83 FOREIGN KEY (USER_ID)
	REFERENCES T_USER (ID);

ALTER TABLE T_USER_ROLE ADD CONSTRAINT FK331DEE5FF26C6BA3 FOREIGN KEY (ROLE_ID)
	REFERENCES T_ROLE (ID);

ALTER TABLE T_ROLE_RESOURCE ADD CONSTRAINT FK379F912CF26C6BA3 FOREIGN KEY (ROLE_ID)
	REFERENCES T_ROLE (ID);

ALTER TABLE T_ROLE_RESOURCE ADD CONSTRAINT FK379F912CF201A823 FOREIGN KEY (RESOURCE_ID)
	REFERENCES T_RESOURCE (ID);

